# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\ndemo.proto\x12\x04\x64\x65mo"\x1e\n\x0bPingRequest\x12\x0f\n\x07message\x18\x01 \x01(\t"\x1c\n\tPongReply\x12\x0f\n\x07message\x18\x01 \x01(\t24\n\x04\x44\x65mo\x12,\n\x04Ping\x12\x11.demo.PingRequest\x1a\x0f.demo.PongReply"\x00\x42&Z$github.com/tylerstamour/client/protob\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "demo_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"Z$github.com/tylerstamour/client/proto"
    _globals["_PINGREQUEST"]._serialized_start = 20
    _globals["_PINGREQUEST"]._serialized_end = 50
    _globals["_PONGREPLY"]._serialized_start = 52
    _globals["_PONGREPLY"]._serialized_end = 80
    _globals["_DEMO"]._serialized_start = 82
    _globals["_DEMO"]._serialized_end = 134
# @@protoc_insertion_point(module_scope)
